# 指定构建环境是Node.js，当前版本是稳定版 (stable),版本这里我们选择最新的长期支持版本（ LTS） 应该就够用了
anguage: node_js
node_js: 
  - lts/*  # 稳定版 (stable) ,最新长期支持版（ - lts/* ）

# 指定缓存模块，可加快编译速度
cache:
  directories:
    - node_modules

# 在构建之前
before_install:
  - export TZ='Asia/Shanghai' # 更改时区
  - npm install -g hexo-cli # 安装hexo环境

#部署环境的安装(安装一个部署插件)
install:
  - npm install
  - npm install hexo-deployer-git --save

before_script:
 # 

# 执行清缓存，生成网页操作
script:
  - hexo clean && hexo g
  - echo ${ENV_TEST}
  
after_script:
  - git config user.name "Leader755"
  - git config user.email "1181012791@qq.com"
  - cd .deploy_git
  - git checkout master
  - cd ../
  - sed -i'' "s~${GH_REF}~${GH_TOKEN}:x-oauth-basic@${GH_REF}~" _config.yml
  - hexo d > log.txt 2>&1
  - cat log.txt | sed "自动构建Travis CI Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
  - echo "自动构建Travis CI Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')" # 构建后输出时间标识
  

# 指定博客源码分支， Travis CI 监控哪一个分支的变动，这里是 master 分支（若博客备份文件和 GitHub Pages 共用一个仓库的话需设置为博客备份文件所在分支）。
branches:
  only:
    - master

# End: Build LifeCycle

# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
# https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    - 1181012791@qq.com
  on_success: change
  on_failure: always

